/// SimoProof Prover — CLI tool called by the TypeScript pipeline.
///
/// Usage:
///   cargo run -p simoproof-prover --release -- --input /tmp/prover-input.json --output /tmp/proof.json
///
/// Reads prover input JSON, runs Risc0 proof, writes proof output JSON.
/// With RISC0_DEV_MODE=true: uses local prover (fast, dev receipts).
/// With BONSAI_API_KEY set:  uses Bonsai cloud prover (Groth16, for on-chain verification).

use anyhow::{Context, Result};
use clap::Parser;
use risc0_zkvm::{default_prover, ExecutorEnv, ProveInfo};
use serde_json;
use std::fs;
use std::path::PathBuf;

use simoproof_prover::{GuestInput, GuestOutput, ProofOutputFile, ProverInputFile};

// Include the guest ELF and IMAGE_ID generated by risc0-build
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

#[derive(Parser, Debug)]
#[command(about = "SimoProof Risc0 prover — generates ZK proof for a discovery")]
struct Args {
    #[arg(long, help = "Path to prover input JSON")]
    input: PathBuf,

    #[arg(long, help = "Path to write proof output JSON")]
    output: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let dev_mode = std::env::var("RISC0_DEV_MODE").unwrap_or_default() == "true";
    if dev_mode {
        println!("[prover] RISC0_DEV_MODE=true (fast dev receipt, not Groth16)");
    } else {
        println!("[prover] Production mode — using Bonsai or local Groth16 prover");
    }

    // Read input
    let input_bytes = fs::read(&args.input)
        .with_context(|| format!("Failed to read input: {:?}", args.input))?;
    let file_input: ProverInputFile = serde_json::from_slice(&input_bytes)
        .context("Failed to parse prover input JSON")?;

    // Build GuestInput
    let guest_input = GuestInput {
        raw_source_bytes:     file_input.raw_source_bytes,
        consensus_vote_count: file_input.consensus_vote_count,
        api_source_hashes:    file_input.api_source_hashes,
        consensus_hash:       file_input.consensus_hash,
        claim:                file_input.claim,
        confidence:           file_input.confidence,
        confidence_threshold: 0.85,
        consensus_threshold:  3,
        timestamp:            file_input.timestamp,
    };

    println!("[prover] Claim: {}...", &guest_input.claim[..guest_input.claim.len().min(60)]);
    println!("[prover] Confidence: {:.2} (threshold: 0.85)", guest_input.confidence);
    println!("[prover] Consensus votes: {} (threshold: 3)", guest_input.consensus_vote_count);

    // Build executor environment — write private+public inputs
    let env = ExecutorEnv::builder()
        .write(&guest_input)
        .context("Failed to write guest input")?
        .build()
        .context("Failed to build executor env")?;

    // Run prover
    println!("[prover] Starting Risc0 prover...");
    let prover     = default_prover();
    // risc0-zkvm 3.0: prove() returns ProveInfo; the Receipt is at .receipt
    let prove_info: ProveInfo = prover
        .prove(env, SIMOPROOF_GUEST_ELF)
        .context("Risc0 prover failed")?;
    let receipt = prove_info.receipt;

    println!("[prover] Proof generated!");

    // Extract journal outputs (public)
    let output: GuestOutput = receipt.journal.decode()
        .context("Failed to decode journal")?;

    println!("[prover] confidence_met={} consensus_met={} causal_valid={}",
        output.confidence_met, output.consensus_met, output.causal_valid);

    // Get seal bytes
    // In dev mode: receipt is a FakeReceipt; in production: Groth16 receipt
    let (seal_bytes, is_groth16) = match receipt.inner.groth16() {
        Ok(g16)  => (g16.seal.clone(), true),
        Err(_)   => {
            // Dev mode: use serialized receipt as "seal" placeholder
            (serde_json::to_vec(&receipt.inner).unwrap_or_default(), false)
        }
    };

    let journal_bytes = receipt.journal.bytes.clone();
    let image_id_hex  = format!("{:?}", SIMOPROOF_GUEST_ID);

    if is_groth16 {
        println!("[prover] Groth16 seal: {} bytes", seal_bytes.len());
    } else {
        println!("[prover] Dev mode receipt: {} bytes (not Groth16 — use BONSAI_API_KEY for production)", seal_bytes.len());
    }

    // Write output
    let proof_out = ProofOutputFile {
        seal:              hex::encode(&seal_bytes),
        journal_bytes:     hex::encode(&journal_bytes),
        image_id:          image_id_hex,
        claim_hash:        hex::encode(output.claim_hash),
        source_commitment: hex::encode(output.source_commitment),
        consensus_hash:    hex::encode(output.consensus_hash),
        confidence_met:    output.confidence_met,
        consensus_met:     output.consensus_met,
        causal_valid:      output.causal_valid,
        timestamp:         output.timestamp,
        dev_mode,
    };

    let out_json = serde_json::to_string_pretty(&proof_out)
        .context("Failed to serialize proof output")?;
    fs::write(&args.output, out_json)
        .with_context(|| format!("Failed to write output: {:?}", args.output))?;

    println!("[prover] Proof written to {:?}", args.output);
    Ok(())
}
